[project]
name = "sovtech-ontology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ontology",
    "tap-pdip",
    "target-oxigraph",
    "target-rdf-file",
    "mypy>=2.1.0",
    "ruff>=0.15.15",
]

[tool.uv.sources]
ontology = { workspace = true }
tap-pdip = { workspace = true }
target-oxigraph = { workspace = true }
target-rdf-file = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/ontology",
    "packages/tap-pdip",
    "packages/target-oxigraph",
    "packages/target-rdf-file",
]

[dependency-groups]
dev = [
    "pyright>=1.1.410",
    "ruff>=0.15.15",
]
