name: Continuous Integration
on: [push]
permissions:
  contents: write
  checks: write
  pull-requests: write
jobs:
  continuous-integration:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.x"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('uv.lock') }}-v3
      - name: Install dependencies
        if: steps.cached-uv-dependencies.outputs.cache-hit != 'true'
        run: script/bootstrap
      - name: Run CI Build
        run: script/cibuild
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results/*.xml
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
            junitxml-path: test-results/junit.xml
            pytest-coverage-path: test-results/coverage.txt